### ISSUE TITLE
Debugging with GDB doesn't work on X86-64 hosted

### ISSUE THREAD

**Issue by mattrust** [aros-development-team/AROS#52]
Run AROS as shown in the debugging manual:
gdb boot/linux/AROSBootstrap

Run Developer/Debug/Test/exec/crashtest

It segfaults but findaddr doesn't work:
Thread 2.1 "AROSBootstrap" received signal SIGSEGV, Segmentation fault.
[Wechseln zu Thread 0x7ffff7fd7740 (LWP 26165)]
0x000000004111d6d4 in ?? ()
(gdb) bt
&#35; 0  0x000000004111d6d4 in ?? ()
&#35; 1  0x0000000041116890 in ?? ()
&#35; 2  0x0000000000000000 in ?? ()
(gdb) findaddr 0x000000004111d6d4
(gdb) findaddr 0x0000000041116890

**Comment by Kalamatee** [comment]
the problem is by default, builds dont have debug information enabled - but GDB uses debug information from AROSBootstrap to get access to the information needed to implement its support functions (findaddr etc..).

I've patched this in trunk so that the debug symbols are always present now for AROSBootstrap.
